use cogy_ecommerce_database;

ALTER TABLE PRODUCT
    ADD COLUMN VOUCHER_ID VARCHAR(36),
ADD CONSTRAINT fk_product_voucher FOREIGN KEY (VOUCHER_ID) REFERENCES VOUCHER (ID);

DROP TABLE VOUCHERS_PRODUCTS;

ALTER TABLE VOUCHER
DROP FOREIGN KEY voucher_ibfk_1;

ALTER TABLE VOUCHER
DROP COLUMN STATUS_ID;

DROP TABLE STATUS;